### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by ojvaj1** [Daniel2193/EmoteDownloader#2]
I don't rly understand how to use this. The exe doesn't open and i don't know what do you.

**Comment by Daniel2193** [comment]
This is a CLI application, meaning you are supposed to run it in a Terminal/Command Prompt. The easiest way to do that is to open the Folder your exe file is in an then typing ```cmd``` in the address bar
![image](https://user-images.githubusercontent.com/23408743/203296096-38b32aca-8128-47d9-8af9-eeb61cc43a7b.png)
Try to use one of the samples from the [Readme File](https://github.com/Daniel2193/EmoteDownloader/blob/master/README.md) and then adjust it to what you want to download
It should look somewhat like this 
![image](https://user-images.githubusercontent.com/23408743/203296918-2a6fdd59-1ce8-4111-8f47-79e911c391e3.png)
